{{- if $.Values.syslog.enabled }}
{{- range $key, $values := .Values.syslog.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-syslog-{{ $values.name }}
  labels:
    {{- with $values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with $values.service }}
  type: {{ .type | default "ClusterIP" }}
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- end }}
  ports:
    - name: {{ .name | default $key }}
      targetPort: {{ $values.containerPort }}
      protocol: {{ $values.protocol | default "TCP" }}
      {{- if $values.service }}
      port: {{ $values.service.port | default $values.containerPort }}
      {{- if $values.service.nodePort }}
      nodePort: {{ $values.service.nodePort }}
      {{- end }}
      {{- else }}
      port: {{ $values.containerPort }}
      {{- end }}
  selector:
    app.kubernetes.io/component: {{ $.Release.Name }}-syslog-ng
{{- end }}
{{- end }}