apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.url }}
  labels:
    {{- include "aci-monitoring-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.port }}
      targetPort: {{ .Values.config.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: {{ $.Release.Name }}-aci-exporter
