{{- if or (and .Values.grafana.enabled .Values.grafana.sidecar.datasources.enabled) .Values.grafana.forceDeployDatasources }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-datasources
  namespace: {{ .Release.Namespace }}
{{- if .Values.grafana.sidecar.datasources.annotations }}
  annotations:
    {{- toYaml .Values.grafana.sidecar.datasources.annotations | nindent 4 }}
{{- end }}
  labels:
    {{ $.Values.grafana.sidecar.datasources.label }}: {{ $.Values.grafana.sidecar.datasources.labelValue | quote }}
    app: {{ .Release.Name }}-grafana
{{ include "aci-monitoring-stack.labels" $ | indent 4 }}
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
{{- $scrapeInterval := .Values.grafana.sidecar.datasources.defaultDatasourceScrapeInterval | default .Values.prometheus.scrapeInterval | default "30s" }}
{{- if .Values.grafana.sidecar.datasources.defaultDatasourceEnabled }}
    - name: {{ .Values.grafana.sidecar.datasources.name }}
      type: prometheus
      uid: {{ .Values.grafana.sidecar.datasources.uid }}
      {{- if .Values.grafana.sidecar.datasources.url }}
      url: {{ .Values.grafana.sidecar.datasources.url }}
      {{- else }}
      url: http://{{ .Release.Name }}-prometheus-server.{{ .Release.Namespace }}.svc:{{ .Values.prometheus.service.servicePort }}/{{ trimPrefix "/" .Values.prometheus.server.prefixURL }}
      {{- end }}
      access: proxy
      isDefault: {{ .Values.grafana.sidecar.datasources.isDefaultDatasource }}
      jsonData:
        httpMethod: {{ .Values.grafana.sidecar.datasources.httpMethod }}
        timeInterval: {{ $scrapeInterval }}
        {{- if .Values.grafana.sidecar.datasources.timeout }}
        timeout: {{ .Values.grafana.sidecar.datasources.timeout }}
        {{- end }}
{{- if .Values.grafana.sidecar.datasources.exemplarTraceIdDestinations }}
        exemplarTraceIdDestinations:
        - datasourceUid: {{ .Values.grafana.sidecar.datasources.exemplarTraceIdDestinations.datasourceUid }}
          name: {{ .Values.grafana.sidecar.datasources.exemplarTraceIdDestinations.traceIdLabelName }}
{{- end }}
{{- if .Values.grafana.sidecar.datasources.alertmanager.enabled }}
    - name: {{ .Values.grafana.sidecar.datasources.alertmanager.name }}
      type: alertmanager
      uid: {{ .Values.grafana.sidecar.datasources.alertmanager.uid }}
      {{- if .Values.grafana.sidecar.datasources.alertmanager.url }}
      url: {{ .Values.grafana.sidecar.datasources.alertmanager.url }}
      {{- else }}
      url: http://{{ .Release.Name }}-alertmanager.{{ .Release.Namespace }}.svc:{{ .Values.prometheus.alertmanager.service.port }}
      {{- end }}
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: {{ .Values.grafana.sidecar.datasources.alertmanager.handleGrafanaManagedAlerts }}
        implementation: {{ .Values.grafana.sidecar.datasources.alertmanager.implementation }}
{{- end }}
{{- end }}

{{- if $.Values.memgraph.enabled }}
    - name: "memgraph"
      type: kniepdennis-neo4j-datasource
      access: proxy
      url: ""
      jsonData: {url: "bolt://{{ $.Release.Name }}-memgraph:{{ $.Values.memgraph.boltPort }}"}
      uid: 'memgraph'
      version: 2
{{- end }}

{{- if $.Values.loki.enabled }}
{{- if .Values.loki.loki.enabled }}
    - name: Loki
      type: loki
      access: proxy
      url: http://{{ template "loki.gatewayFullname" .Subcharts.loki }}:{{ .Values.loki.loki.gateway.service.port }}
      version: 1
      isDefault: {{ default false .Values.loki.loki.isDefault }}
      {{- with .Values.loki.loki.datasource.uid }}
      uid: {{ . | quote }}
      {{- end }}
      {{- with .Values.loki.loki.datasource.jsonData }}
      jsonData:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
{{- end }}

{{- end }}

{{- end }}