{{- $files := .Files.Glob "config.d/*.yaml" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-aci-exporter
  labels:
    app.kubernetes.io/component: {{ $.Release.Name }}-aci-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ $.Release.Name }}-aci-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ $.Release.Name }}-aci-exporter
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-aci-exporter-config.yaml") . | sha256sum }}
        {{- if $files }}
        {{- range $path, $fileContents := $files }}
        {{- $configName := regexReplaceAll "(^.*/)(.*)\\.yaml$" $path "${2}" }}
        checksum/queries-{{ $configName }}: {{ print $fileContents | sha256sum }}
        {{- end }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.config.port }}
              protocol: TCP
          volumeMounts:
          - name: {{ $.Release.Name }}-aci-exporter-config
            mountPath: /etc/aci-exporter/config.yaml
            subPath: config.yaml
          {{- if $files }}
          {{- range $path, $fileContents := $files }}
          {{- $configName := regexReplaceAll "(^.*/)(.*)\\.yaml$" $path "${2}" }}
          - name: {{ printf "%s-aci-exporter-queries-%s" $.Release.Name $configName | trunc 63 | trimSuffix "-" }}
            mountPath: /etc/aci-exporter/config.d/{{ $configName }}.yaml
            subPath: {{ $configName }}.yaml
          {{- end }}
          {{- end }}
      volumes:
      - name: {{ $.Release.Name }}-aci-exporter-config
        configMap:
          name: {{ $.Release.Name }}-aci-exporter-config
      {{- if $files }}
      {{- range $path, $fileContents := $files }}
      {{- $configName := regexReplaceAll "(^.*/)(.*)\\.yaml$" $path "${2}" }}
      - name: {{ printf "%s-aci-exporter-queries-%s" $.Release.Name $configName | trunc 63 | trimSuffix "-" }}
        configMap:
          name: {{ printf "%s-aci-exporter-queries-%s" $.Release.Name $configName | trunc 63 | trimSuffix "-" }}
      {{- end }}
      {{- end }}