apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
  labels:
    app: {{ .Release.Name }}-prometheus-alerts
{{ include "aci-monitoring-stack.labels" $ | indent 4 }}
data:
  prometheus-alerts.yaml: {{ $.Files.Get "alerts/prom/alerts.yaml" | toYaml | indent 4 }}