{{- if $.Values.grafana.sidecar.datasources.enabled }}
{{- if $.Values.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-loki-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ template "aci-monitoring-stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if $.Values.grafana.sidecar.datasources.label }}
    {{ $.Values.grafana.sidecar.datasources.label }}: {{ $.Values.grafana.sidecar.datasources.labelValue | quote }}      
    {{- else }}
    grafana_datasource: "1"
    {{- end }}
data:
  loki-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
{{- if .Values.loki.loki.enabled }}
    - name: Loki
      type: loki
      access: proxy
      url: http://{{ template "loki.gatewayFullname" .Subcharts.loki }}:{{ .Values.loki.loki.gateway.service.port }}
      version: 1
      isDefault: {{ default false .Values.loki.loki.isDefault }}
      {{- with .Values.loki.loki.datasource.uid }}
      uid: {{ . | quote }}
      {{- end }}
      {{- with .Values.loki.loki.datasource.jsonData }}
      jsonData:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
{{- end }}

{{- end }}
{{- end }}